### ISSUE TITLE
Not able to download LFS file

### ISSUE THREAD

**Issue by sandlogic** [IAmWave/acres#3]
Hi 

Not able to clone the repo as we get the quota error:  This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Please let me know if can share a gift card or purchase quota for you so that I can download the file or please let me know if you can share the same via google drive or onedrive.

Cheers
Kamal

**Comment by RiaanLab** [comment]
Hi,
Same issue here. If I can buy a giftcard please let me know. 

Sharing via Google, Azure, etc would also be great.
Regards
Riaan

**Comment by IAmWave** [comment]
I believe this might be due to my GitHub educational discount expiring. I've re-applied over a month ago, but GitHub hasn't responed yet; I've just sent them a support request regarding this.

In the meanwhile, I've uploaded a zip of the repo to [Google Drive](https://drive.google.com/file/d/1xMRg5XTwtXEluVM7Tpwj0PAQ_X4VL5Jf/view?usp=sharing). Does this suffice?

**Comment by sandlogic** [comment]
> I believe this might be due to my GitHub educational discount expiring. I've re-applied over a month ago, but GitHub hasn't responed yet; I've just sent them a support request regarding this.
> 
> In the meanwhile, I've uploaded a zip of the repo to [Google Drive](https://drive.google.com/file/d/1xMRg5XTwtXEluVM7Tpwj0PAQ_X4VL5Jf/view?usp=sharing). Does this suffice?

Thank you. Will help and will definitely revert in case I hit any block.

Cheers
Kamal

**Comment by RiaanLab** [comment]
Excellent. Much appreciated @IAmWave

**Comment by AneeshDN** [comment]
@IAmWave 

Thanks for uploading the repo in [GoogleDrive](https://drive.google.com/file/d/1xMRg5XTwtXEluVM7Tpwj0PAQ_X4VL5Jf/view)

I am able to setup the codebase. But when am running the training locally, I am getting the error attached 
![temp](https://user-images.githubusercontent.com/2006898/79331036-2b535880-7f38-11ea-80ed-a09bee174449.PNG)

I am not able to open the images in these folders "acres\data\muenster_blur\images", "acres\data\muenster_blur\masks" and "acres\data\muenster_blur\masks_orig".

Let me know if you need more info on the Python environment. Also, Let me know if I need to create a new issue. Thanks.

Best Regards,
Aneesh Nagaraj

**Comment by IAmWave** [comment]
Ah, I see the situation is more difficult than I thought: I cloned the repo successfully, but the LFS files (JPGs) were replaced with files such as

```
version https://git-lfs.github.com/spec/v1
oid sha256:9977a8add299d1ba96ec20042b7930956e905b1efbdc1056af1641f1a88a7341
size 53796
```

I paid GitHub what they wanted (it's quite cheap) and my quota was reset, so you should be able to clone the repo successfully now.

**Comment by AneeshDN** [comment]
Thank you @IAmWave . I am able to access the JPGs and run the training successfully.

Can you provide your email address, I will be reaching out to you if any clarification is required. Thanks.

Best Regards,
Aneesh

**Comment by IAmWave** [comment]
I'm glad you're interested in the repo. If you run into trouble, please simply open another issue.
